services:
  ucms_web:
    init: true
    build:
      context: ./UCMS_WebServer
      dockerfile: Dockerfile
      target: dev
    container_name: dev_ucms_web
    restart: always
    environment:
      NODE_ENV: dev
      DB_HOST: mysql
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

    env_file:
      - ./UCMS_WebServer/keys/.env.dev
    volumes:
      - ./UCMS_WebServer/keys/google:/app/keys/google
      - ./UCMS_WebServer:/app
      - /app/node_modules

  ucms_sharedb:
    init: true
    build:
      context: ./UCMS_ShareDB
      dockerfile: Dockerfile
      target: dev
    container_name: dev_ucms_sharedb
    restart: always
    environment:
      NODE_ENV: dev
      DB_HOST: mysql
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    env_file:
      - ./UCMS_ShareDB/keys/.env.dev
    volumes:
      - ./UCMS_ShareDB:/app
      - /app/node_modules

networks:
  default:
    name: UCMS-network
    external: true