services:
  mysql:
    image: mysql:8
    command: --lower_case_table_names=1 # 1로 설정하면 대소문자 구분 안 함
    container_name: ucms_mysql
    restart: always
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    env_file:
      - ./env/db.env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mysql --protocol=TCP -h 127.0.0.1 -u healthcheck -p"$${MYSQL_HEALTHCHECK_PASSWORD}" -e ''SELECT 1'' >/dev/null 2>&1',
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - prod-db
      - dev-db

  nginx:
    image: nginx:latest
    container_name: ucms_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-1.28.0/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-1.28.0/conf/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./logs:/var/log/nginx
    networks:
      - prod-app
      - dev-app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ../prod/data/certbot/conf:/etc/letsencrypt
      - ../prod/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

# docker 내부 mysql 저장소 설정
volumes:
  mysql_data:
    name: umcs-mysql-data

# 네트워크 전체를 infra 에서 관리
networks:
  dev-app:
    name: ucms-dev-app-network
  prod-app:
    name: ucms-prod-app-network
  dev-db:
    name: ucms-dev-db-network
  prod-db:
    name: ucms-prod-db-network
