services:
  mysql:
    image: mysql:8
    command: --lower_case_table_names=1  # 1로 설정하면 대소문자 구분 안 함
    container_name: ucms_mysql
    restart: always
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    env_file:
      - ./MySQL/keys/.env.prod
    volumes:
      - ./initialData.sql:/docker-entrypoint-initdb.d/backup.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ucms_web:
    init: true
    image: gyangho/ucms_web:latest
    container_name: ucms_web
    restart: always
    environment:
      NODE_ENV: prod
      DB_HOST: mysql
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    env_file:
      - ./UCMS_WebServer/keys/.env.prod
    volumes:
      - ./UCMS_WebServer/keys/google:/app/keys/google
      - ./UCMS_WebServer/InterviewScheduler:/app/InterviewScheduler
      - ./UCMS_WebServer/interview_place.csv:/app/interview_place.csv
    depends_on:
      mysql:
        condition: service_healthy

  ucms_sharedb:
    init: true
    image: gyangho/ucms_sharedb:latest
    container_name: ucms_sharedb
    restart: always
    environment:
      NODE_ENV: prod
      DB_HOST: mysql
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    env_file:
      - ./UCMS_ShareDB/keys/.env.prod
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: ucms_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-1.28.0/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-1.28.0/conf/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./logs:/var/log/nginx
    depends_on:
      - ucms_web
      - ucms_sharedb

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  mysql_data:

networks:
  default:
    name: UCMS-network
    external: true