# 도커 내부 DNS
resolver 127.0.0.11 valid=30s;

# 미등록 도메인 차단
server {
    listen 80 default_server;
    server_name _;
    return 444;
}

server {
    listen 443 ssl default_server;
    ssl_reject_handshake on;
    server_name _;
}

# HTTP → HTTPS 리다이렉트
server {
    listen 80;
    server_name ucms.gyangho.ddns.net dev-ucms.gyangho.ddns.net localhost;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}